# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2023.05.30-h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2021.4.0-h06a4308_3561.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran5-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-11.2.0-h00389a5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2021.4.0-h06a4308_640.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.19.0-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.4.9-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libev-4.33-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1u-h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20221030-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnghttp2-1.52.0-ha637b67_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.10.0-h37d81fd_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.12-h1ccaba5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.20.1-h568e23c_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.41.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-8.1.1-h91b91d3_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.8.13-haa1d7c7_1.conda
https://repo.anaconda.com/pkgs/main/noarch/appdirs-1.4.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2023.5.7-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cmake-3.11.1-h307fef2_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.4-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-23.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2022.7-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-67.8.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.38.4-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.1-py38h74dc2b5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py38h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-23.1.2-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py38h27cfd23_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-39.0.1-py38h9ce1e76_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.24.3-py38h31eccc5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-23.0.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.16-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.29.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pooch-1.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.1-py38hd3c417c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.2-py38h51133e4_0.conda
# https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.24.3-py38h14f4228_0.conda
# https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.10.1-py38h14f4228_0.conda
